version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: db_controlestacionamiento
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
    ports: 
        - 33061:3306
    networks:
      - default
  phpmyadmin:
    container_name: shopcart_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8012:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php7-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
      - ./config:/usr/local/etc/php
    links:
      - db
    networks:
      - default